/* Verify the real published staff journey with fictional data only. */
'use strict';
const fs=require('fs'),path=require('path');
const {launch,root}=require('./browser-support');
const release=path.resolve(root,'../release-2026-09-11-v2.3');
const out=path.resolve(root,'../docs/audit-2026-09-11-imports');
const mode=process.argv[2]||'chromium';
const base=process.argv.includes('--local')?'http://127.0.0.1:4198':'https://www.ish.academy';
const checks=[];
function check(name,pass,detail){checks.push({name,pass:!!pass,...(!pass?{detail}:{} )});console.log((pass?'PASS ':'FAIL ')+name);}
(async()=>{let browser;
try{
 browser=await launch(mode);const page=await browser.newPage({viewport:{width:1440,height:1000},locale:'en-GB'});const errors=[],processingRequests=[];let processing=false;
 page.on('pageerror',e=>errors.push(e.message));page.on('requestfinished',r=>{if(processing&&/^https?:/.test(r.url()))processingRequests.push(r.url());});page.on('dialog',d=>d.accept());
 await page.goto(base+'/innovate/');
 await page.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>a.effect?.getComputedTiming().endTime<Infinity).map(a=>a.finished.catch(()=>{})));});
 check('Innovate shows eight tool/resource cards',await page.locator('article.innovate-card').count()===8);
 const baseline=fs.readFileSync(path.join(release,'backup/innovate-index.html'),'utf8');
 const priorLinks=[...baseline.matchAll(/href="([^"]+)"/g)].map(m=>m[1]);
 const links=await page.locator('[href]').evaluateAll(xs=>xs.map(x=>x.getAttribute('href')));
 check('All previous Innovate links remain',priorLinks.every(x=>links.includes(x.replace('/innovate/pii-shield/','/privacy/'))));
 await page.evaluate(fs.readFileSync(require.resolve('axe-core/axe.min.js'),'utf8'));
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});const violations=await page.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)})));check('Innovate accessibility '+width,violations.length===0,violations);check('Innovate no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'release-'+mode+'-hub-'+width+'.png'),fullPage:true});}
 await page.getByRole('link',{name:'Open AI Privacy',exact:true}).click();await page.waitForFunction(()=>document.getElementById('stepbtn-1')?.getAttribute('aria-current')==='step');
 check('Public Innovate link opens the working tool',new URL(page.url()).pathname==='/privacy/');processing=true;
 await page.check('#mode-codes');await page.click('#try-example');await page.click('#to-step-2');const original=await page.textContent('#preview');check('Live example detects name birth date address and contacts',await page.locator('#preview mark').count()>=5);check('Live review acknowledgement is required',await page.locator('#to-step-3').isDisabled());await page.check('#review-confirm');await page.click('#to-step-3');const safe=await page.textContent('#anon-output');check('Live example replaces the identifying text',safe.includes('[[PERSON_')&&!safe.includes('Sofia')&&!safe.includes('14 March')&&!safe.includes('2554'));check('Live sharing acknowledgement is required',await page.locator('#copy-safe').isDisabled());await page.click('#to-step-5');await page.fill('#ai-text',safe);await page.click('#do-restore');check('Live example restores exactly',(await page.textContent('#restore-output'))===original);await page.click('#start-over');
 await page.click('#filename-tool summary');await page.fill('#filename-list','Sofia_Marin_2010-03-14.pdf\n李_王_12345.xlsx');await page.click('#check-filenames');check('Live filename list replaces both whole names',await page.locator('#preview mark').count()===2);await page.check('#review-confirm');await page.click('#to-step-3');const names=await page.textContent('#anon-output');check('Live filenames exclude names dates and IDs',names.split('[REMOVED]').length===3&&!names.includes('2010')&&!names.includes('12345'));await page.click('#start-over');
 await page.fill('#input-text','A report for Sofia Marin.');await page.fill('#ai-task','Summarise for parent@example.org, DOB: 2009/03/09.');await page.click('#to-step-2');check('Live request is included in detection',(await page.locator('#preview mark').allTextContents()).includes('parent@example.org'));await page.check('#review-confirm');await page.click('#to-step-3');const removed=await page.textContent('#anon-output');check('Live default removes request and source identifiers',removed.includes('[REMOVED]')&&!removed.includes('parent@example.org')&&!removed.includes('2009')&&!removed.includes('Sofia'));check('Live removal clears source request and private preview',(await page.inputValue('#input-text'))===''&&(await page.inputValue('#ai-task'))===''&&(await page.textContent('#preview'))==='');check('Live removal offers no restoration route',!(await page.locator('#to-step-5').isVisible())&&!(await page.locator('#stepbtn-5').isEnabled()));await page.click('#start-over');
 await page.setInputFiles('#file-input',path.join(out,'fixtures/example.docx'));await page.waitForFunction(()=>document.getElementById('input-text').value.includes('Elena Rossi'));check('Live hosted Word parser extracts text and filename',(await page.inputValue('#input-text')).includes('example.docx'));
 const XLSX=require('../vendor/1_xlsx.full.min.js'),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Name','Date of birth'],['Amir Haddad','2009-11-23']]),'Admissions');await page.setInputFiles('#file-input',{name:'Amir_Haddad.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))});await page.waitForFunction(()=>document.getElementById('input-text').value.includes('Amir Haddad'));check('Live hosted Excel parser extracts text and birth date',(await page.inputValue('#input-text')).includes('2009-11-23'));
 await page.setInputFiles('#file-input',path.join(root,'tests/fixtures/201-pages.pdf'));await page.waitForFunction(()=>document.getElementById('file-note').textContent.includes('200 pages'));check('Live hosted PDF parser enforces page limit without replacing source',(await page.inputValue('#input-text')).includes('Amir Haddad'));await page.click('#start-over');
 await page.click('#open-help');check('Live English tutorial has six steps and eighteen FAQs',await page.locator('.guide-steps>li').count()===6&&await page.locator('.faq').count()===22);await page.click('#lang-toggle');check('Live Dutch guide includes staff roles and filename guidance',(await page.textContent('#help-content')).includes('Leerlingondersteuning')&&(await page.textContent('#help-content')).includes('bestandsnamen'));await page.click('#lang-toggle');await page.click('#close-help');
 await page.evaluate(fs.readFileSync(require.resolve('axe-core/axe.min.js'),'utf8'));
 for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});const violations=await page.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)})));check('Live tool accessibility '+width,violations.length===0,violations);check('Live tool no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'release-'+mode+'-tool-'+width+'.png'),fullPage:true});}
 check('No requests complete during document processing',processingRequests.length===0,processingRequests);check('No application exceptions',errors.length===0,errors);check('Clear session leaves no document text',(await page.inputValue('#input-text'))==='');
}catch(error){checks.push({name:'Release journey completes',pass:false,detail:error.stack,errorCategory:'validation',isRetryable:false});}
finally{if(browser)await browser.close();const result={browser:mode,base,checkedAt:new Date().toISOString(),passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,checks};fs.writeFileSync(path.join(out,'release-'+mode+(base.startsWith('http:')?'-local':'-live')+'-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({browser:mode,passed:result.passed,failed:result.failed}));process.exitCode=result.failed?1:0;}
})();
