/* Real staff journeys and regressions against the shipped single HTML file. Synthetic data only. */
'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const {launch,serve,root}=require('./browser-support');
const mode=process.argv[2]||'chromium', out=path.resolve(root,'../docs/audit-2026-09-11-imports');fs.mkdirSync(out,{recursive:true});
const results=[],requests=[],pageErrors=[];
function check(name,condition,detail){results.push({name,pass:!!condition,...(!condition?{detail}:{} )});console.log((condition?'PASS ':'FAIL ')+name+(!condition&&detail?' '+JSON.stringify(detail):''));}
function pdfBytes(text){let objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 800] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];const data=text?'BT /F1 12 Tf 50 730 Td ('+text.replace(/[()\\]/g,'\\$&')+') Tj ET':'0 0 1 rg 10 10 100 100 re f';objects.push('<< /Length '+Buffer.byteLength(data)+' >>\nstream\n'+data+'\nendstream');let s='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(s));s+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=Buffer.byteLength(s);s+='xref\n0 '+offsets.length+'\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Root 1 0 R /Size '+offsets.length+' >>\nstartxref\n'+xref+'\n%%EOF';return Buffer.from(s);}
(async()=>{
 const {server,url}=await serve();let browser;
 try{
  browser=await launch(mode);const context=await browser.newContext({viewport:{width:1440,height:1080},locale:'en-GB',colorScheme:'light'});const page=await context.newPage();
  page.on('request',r=>{if(!r.url().startsWith(new URL(url).origin)&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))requests.push(r.url());});page.on('pageerror',e=>pageErrors.push(e.message));page.on('dialog',d=>d.accept());page.setDefaultTimeout(30000);
  await page.goto(url+'#guide');check('Direct tutorial link opens the guide',await page.locator('#help-panel').isVisible());await page.click('#close-help');check('App initializes',await page.locator('#stepbtn-1').getAttribute('aria-current')==='step');check('No remote model loader',await page.evaluate(()=>!window.PIINER));
  check('Copy/review/restore cannot be reached from blank source',!(await page.locator('#stepbtn-3').isEnabled())&&!(await page.locator('#stepbtn-5').isEnabled()));
  await page.click('#to-step-2');check('Empty input has an explicit result',(await page.locator('#app-message').textContent()).includes('text'));
  await page.check('#mode-codes');await page.click('#try-example');await page.fill('#ai-task','Write a concise summary.');await page.click('#to-step-2');const original=await page.textContent('#preview');check('Name, birth date, address and contact details found',(await page.locator('#preview mark').count())>=5);
  check('Review acknowledgement gates next step',!(await page.locator('#to-step-3').isEnabled()));
  await page.check('#review-confirm');await page.click('#to-step-3');const replaced=await page.textContent('#anon-output');
  check('Explicit tokens replace fictional identifiers',/\[\[PERSON_\d+\]\]/.test(replaced)&&!replaced.includes('Sofia')&&!replaced.includes('2554')&&!replaced.includes('14 March'));
  check('Sharing acknowledgement gates clipboard',!(await page.locator('#copy-safe').isEnabled()));
  await page.check('#share-confirm');
  check('Prompt preserves codes and avoids invented facts',(await page.textContent('#prompt-output')).includes('Do not invent facts')&&(await page.textContent('#prompt-output')).includes('Write a concise summary.'));
  const downloadPromise=page.waitForEvent('download');await page.click('#download-safe');const download=await downloadPromise;const downloadPath=await download.path();check('Downloaded prompt includes request, instructions and reviewed text',fs.readFileSync(downloadPath,'utf8')===await page.textContent('#prompt-output'));
  await page.click('#to-step-5');await page.fill('#ai-text',replaced);await page.click('#do-restore');check('Full UI round-trip restores exact source',(await page.textContent('#restore-output'))===original);check('Clean round-trip has no warning',!(await page.locator('#flagged-panel').isVisible()));
  await page.fill('#ai-text','An edited reply.');check('Editing the reply clears stale restored output',!(await page.locator('#restore-wrap').isVisible()));await page.click('#do-restore');check('Reply without codes has explicit warning',await page.locator('#flagged-panel').isVisible());
  await page.fill('#ai-text','[[PERSON_9999]] submitted.');await page.click('#do-restore');check('Unknown token never becomes an identity',(await page.textContent('#restore-output')).includes('[[PERSON_9999]]')&&await page.locator('#flagged-panel').isVisible());
  await page.click('#stepbtn-1');await page.fill('#input-text','A fresh report for Amir Haddad.');check('Source edit invalidates prior review and restoration',!(await page.locator('#stepbtn-3').isEnabled())&&!(await page.locator('#stepbtn-5').isEnabled())&&(await page.textContent('#anon-output'))==='');
  await page.click('#to-step-2');await page.fill('#manual-value','Amir Haddad');await page.selectOption('#manual-type','name');await page.click('#add-manual');check('Overlapping manual full name becomes real highlighted span',(await page.locator('#preview mark').allTextContents()).includes('Amir Haddad'));
  await page.fill('#manual-value','Does not exist');await page.click('#add-manual');check('Missing manual text is not silently added',(await page.textContent('#manual-note')).includes('not found'));
  await page.check('#review-confirm');await page.click('#to-step-3');check('Manual redaction removes full overlapping name',!(await page.textContent('#anon-output')).includes('Haddad'));
  await page.click('#back-to-2');await page.click('#detection-options summary');const first=page.locator('#review-tbody input').first();await first.click();check('Changing a replacement cancels review acknowledgement',!(await page.locator('#review-confirm').isChecked()));await page.click('#stepbtn-1');await page.click('#stepbtn-2');check('Navigating back preserves manual decisions',!(await page.locator('#review-tbody input').first().isChecked()));
  await page.click('#start-over');await page.check('#mode-codes');check('Clear session removes all personal text from hidden DOM',await page.evaluate(()=>!['input-text','preview','review-tbody','anon-output','ai-text','restore-output','manual-value'].some(id=>{const el=document.getElementById(id);return (el.value||el.textContent).includes('Amir')||(el.value||el.textContent).includes('Sofia');})));
  await page.click('#filename-tool summary');await page.fill('#filename-list','Sofia_Marin_2010-03-14.pdf\n李_王_12345.xlsx');await page.click('#check-filenames');check('File-name list marks two whole names',await page.locator('#preview mark').count()===2);const fileListSource=await page.textContent('#preview');await page.check('#review-confirm');await page.click('#to-step-3');const fileListSafe=await page.textContent('#anon-output');check('File-name list removes names, DOB and identifiers',!fileListSafe.includes('Sofia')&&!fileListSafe.includes('2010')&&!fileListSafe.includes('12345'));await page.click('#to-step-5');await page.fill('#ai-text',fileListSafe);await page.click('#do-restore');check('File-name list restores exactly',(await page.textContent('#restore-output'))===fileListSource);await page.click('#start-over');await page.check('#mode-codes');check('Clear session removes filename list',(await page.inputValue('#filename-list'))==='');
  // Name lists across writing systems and multiple staff roles.
  await page.setInputFiles('#csv-input',{name:'names.csv',mimeType:'text/csv',buffer:Buffer.from('first_name,last_name\nМария,Иванова\n李,王\nأحمد,خالد\n')});await page.waitForFunction(()=>document.getElementById('csv-count').textContent.includes('3'));check('Name list keeps three distinct writing systems',(await page.textContent('#csv-count')).includes('3'));
  const multilingual='Мария Иванова; 李 王; أحمد خالد';await page.fill('#input-text',multilingual);await page.click('#to-step-2');await page.check('#review-confirm');await page.click('#to-step-3');const nonLatin=await page.textContent('#anon-output');check('Provided names in Cyrillic Chinese Arabic are replaced',!/[\u0400-\u04ff\u4e00-\u9fff\u0600-\u06ff]/.test(nonLatin));await page.click('#to-step-5');await page.fill('#ai-text',nonLatin);await page.click('#do-restore');check('Multiscript UI round-trip is exact',(await page.textContent('#restore-output')).endsWith('\n'+multilingual));
  await page.click('#start-over');await page.check('#mode-codes');await page.setInputFiles('#file-input',{name:'Elena_Rossi_2010-03-14.txt',mimeType:'text/plain',buffer:Buffer.from('<img src="https://example.invalid/leak" onerror="alert(1)"> Elena Rossi, DOB: 14/03/2010')});await page.waitForFunction(()=>document.getElementById('input-text').value.includes('Elena'));await page.click('#to-step-2');check('Imported HTML is rendered as text, never executed',await page.locator('#preview img').count()===0);check('Imported document filename is covered completely',(await page.locator('#preview mark').allTextContents()).some(x=>x.includes('Elena_Rossi_2010-03-14.txt')));await page.click('#back-to-1');
  await page.setInputFiles('#file-input',{name:'fixture.pdf',mimeType:'application/pdf',buffer:pdfBytes('Sofia Marin born 14 March 2010')});await page.waitForFunction(()=>document.getElementById('input-text').value.includes('Sofia Marin born'));check('Real PDF text extraction works under CSP',(await page.inputValue('#input-text')).includes('14 March 2010'));
  const limitPrior=await page.inputValue('#input-text');await page.setInputFiles('#file-input',path.join(__dirname,'fixtures','201-pages.pdf'));await page.waitForFunction(()=>document.getElementById('file-note').textContent.includes('200 pages'));check('PDF page limit has a clear message and preserves text',(await page.inputValue('#input-text'))===limitPrior);
  const prior=await page.inputValue('#input-text');await page.setInputFiles('#file-input',{name:'scan.pdf',mimeType:'application/pdf',buffer:pdfBytes('')});await page.waitForFunction(()=>document.getElementById('file-note').textContent.includes('No readable'));check('Image-only PDF has a specific outcome and preserves source',(await page.inputValue('#input-text'))===prior);
  await page.setInputFiles('#file-input',{name:'broken.docx',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',buffer:Buffer.from('not a docx')});await page.waitForFunction(()=>document.getElementById('file-note').textContent.includes('could not'));check('Failed Office import preserves previous text',(await page.inputValue('#input-text'))===prior);
  const {execFileSync}=require('child_process');const fixtureDir=path.join(out,'fixtures');fs.mkdirSync(fixtureDir,{recursive:true});execFileSync('python3',[path.join(__dirname,'make-office-fixture.py'),path.join(fixtureDir,'example.docx')]);await page.setInputFiles('#file-input',path.join(fixtureDir,'example.docx'));await page.waitForFunction(()=>document.getElementById('input-text').value.includes('Elena Rossi'));check('Real Word text extraction works',(await page.inputValue('#input-text')).includes('DOB: 14/03/2010'));
  const XLSX=require('../vendor/1_xlsx.full.min.js');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Name','Date of birth'],['Amir Haddad','2009-11-23']]),'Admissions');await page.setInputFiles('#file-input',{name:'example.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))});await page.waitForFunction(()=>document.getElementById('input-text').value.includes('Amir Haddad'));check('Real Excel text extraction works',(await page.inputValue('#input-text')).includes('2009-11-23'));
  const tooLarge=path.join(fixtureDir,'too-large.txt');fs.writeFileSync(tooLarge,Buffer.alloc(50*1024*1024+1,65));await page.setInputFiles('#file-input',tooLarge);await page.waitForFunction(()=>document.getElementById('file-note').textContent.includes('50 MB'));check('Oversized file rejected explicitly',(await page.inputValue('#input-text')).includes('Amir Haddad'));
  await page.fill('#input-text','x'.repeat(100001));await page.click('#to-step-2');check('Oversized pasted text is not processed',(await page.textContent('#app-message')).includes('100,000'));
  await page.click('#start-over');await page.check('#mode-codes');
  for(const role of ['teaching','support','admin']){await page.selectOption('#example-kind',role);await page.click('#try-example');check('Practice example loads for '+role,(await page.inputValue('#input-text')).length>150);await page.click('#start-over');await page.check('#mode-codes');}
  // Full tutorial / FAQ stays local, including print output without original content.
  await page.fill('#input-text','PRIVATE-TEST-SENTINEL');await page.click('#open-help');check('Tutorial has sequential steps and full FAQ',await page.locator('.guide-steps>li').count()===6&&await page.locator('.faq').count()>=16);await page.locator('.faq').nth(2).locator('summary').click();check('GDPR FAQ explains tool is not school approval',(await page.locator('.faq').nth(2).innerText()).includes('lawful'));
  await page.emulateMedia({media:'print'});check('Print view excludes original input',!(await page.locator('#input-text').isVisible()));if(mode==='chromium'){await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));await page.pdf({path:path.join(out,'PII_Shield_Staff_Guide_EN.pdf'),format:'A4',printBackground:true,tagged:true});}await page.emulateMedia({media:'screen'});
  await page.click('#lang-toggle');check('Dutch chrome and guide translate',await page.getAttribute('html','lang')==='nl'&&(await page.textContent('#help-content')).includes('Leerlingondersteuning'));if(mode==='chromium'){await page.emulateMedia({media:'print'});check('Dutch PDF uses private-content-free print layout',!(await page.locator('.topbar').isVisible())&&!(await page.locator('#input-text').isVisible()));await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));await page.pdf({path:path.join(out,'PII_Shield_Staff_Guide_NL.pdf'),format:'A4',printBackground:true,tagged:true});await page.emulateMedia({media:'screen'});}
  await page.click('#close-help');await page.click('#start-over');await page.check('#mode-codes');await page.click('#try-example');await page.click('#to-step-2');await page.check('#review-confirm');await page.click('#to-step-3');check('Dutch workflow says Samenwerken met AI',(await page.textContent('#h-step3'))==='Samenwerken met AI');await page.click('#start-over');await page.check('#mode-codes');await page.click('#lang-toggle');
  // Accessibility and actual responsive screens on each engine.
  await page.evaluate(fs.readFileSync(require.resolve('axe-core/axe.min.js'),'utf8'));
  for(const [width,scheme] of [[1440,'light'],[768,'light'],[390,'light'],[375,'dark']]){
   await page.setViewportSize({width,height:1050});await page.emulateMedia({colorScheme:scheme});
   const audit=await page.evaluate(async()=>({overflow:document.documentElement.scrollWidth>innerWidth,violations:(await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))}));
   check('No horizontal overflow '+width+' '+scheme,!audit.overflow);check('Accessibility '+width+' '+scheme,audit.violations.length===0,audit.violations);
   await page.screenshot({path:path.join(out,mode+'-'+width+'-'+scheme+'.png'),fullPage:true});
  }
  await page.setViewportSize({width:1440,height:1050});await page.emulateMedia({colorScheme:'light'});
  await page.click('#try-example');
  for(const step of [2,3,5,'help']){
   if(step===2)await page.click('#to-step-2');
   if(step===3){await page.check('#review-confirm');await page.click('#to-step-3');}
   if(step===5){await page.click('#to-step-5');await page.fill('#ai-text','[[PERSON_9999]]');await page.click('#do-restore');}
   if(step==='help')await page.click('#open-help');
   const violations=await page.evaluate(async()=> (await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})));
   check('Accessibility on workflow '+step,violations.length===0,violations);
  }
  await page.click('#close-help');await page.click('#start-over');await page.check('#mode-codes');
  await page.click('#readability');await page.click('#contrast-toggle');await page.setViewportSize({width:390,height:1050});check('Reading/contrast controls work without storage',await page.locator('body').getAttribute('class')==='reading contrast');
  await page.setViewportSize({width:720,height:800});await page.evaluate(()=>document.documentElement.style.fontSize='200%');check('200% text enlargement has no page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.evaluate(()=>document.documentElement.style.fontSize='');await page.keyboard.press('Tab');check('Keyboard focus is visible and actionable',await page.evaluate(()=>document.activeElement!==document.body&&getComputedStyle(document.activeElement).outlineStyle!=='none'));
  check('No runtime exceptions',pageErrors.length===0,pageErrors);check('Zero unexpected external requests',requests.length===0,requests);
  check('No local storage session storage or cookies',await page.evaluate(()=>localStorage.length===0&&sessionStorage.length===0&&document.cookie===''));
  await context.setOffline(true);await page.click('#try-example');await page.click('#to-step-2');check('Detection works after disconnecting network',await page.locator('#preview mark').count()>0);
  const diskContext=await browser.newContext();const disk=await diskContext.newPage();const diskRequests=[];disk.on('request',r=>{if(/^https?:/.test(r.url()))diskRequests.push(r.url());});await disk.goto(pathToFileURL(path.join(root,'pii-shield.html')).href);await diskContext.setOffline(true);await disk.click('#try-example');await disk.click('#to-step-2');check('Local HTML loads without network requests and works offline',diskRequests.length===0&&await disk.locator('#preview mark').count()>0);check('Offline copy does not offer a broken repeat download',!(await disk.locator('#download-offline').isVisible()));
  await browser.close();browser=null;
 }catch(error){check('Browser suite completes',false,error.stack);}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));const failed=results.filter(r=>!r.pass);const summary={browser:mode,checkedAt:new Date().toISOString(),passed:results.length-failed.length,failed:failed.length,results};fs.writeFileSync(path.join(out,mode+'-browser-results.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify({browser:mode,passed:summary.passed,failed:summary.failed}));process.exitCode=failed.length?1:0;}
})();
